//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_ModelDetaile
    {
        public string ID { get; set; }
        public string ModelId { get; set; }
        public string Name { get; set; }
        public string LinkAdvertiseId { get; set; }
        public Nullable<int> OrderSort { get; set; }
        public short TargetType { get; set; }
        public short ActiveType { get; set; }
        public string TargetName { get; set; }
    }
}
