//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_Model
    {
        public string ID { get; set; }
        public string AdvertiseId { get; set; }
        public Nullable<int> ModelNum { get; set; }
        public int ModelSort { get; set; }
        public string ModelPic { get; set; }
        public Nullable<int> ImgWitdh { get; set; }
        public Nullable<int> ImgHeight { get; set; }
    }
}
