//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_Section
    {
        public string ID { get; set; }
        public int SectionNum { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> TempleId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RunTime { get; set; }
        public Nullable<bool> IsDeposit { get; set; }
        public string CreaterId { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
