//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoMarket_PromptlyConfig
    {
        public string ID { get; set; }
        public Nullable<byte> MarketType { get; set; }
        public string CompanyId { get; set; }
        public Nullable<byte> ActivitySelect { get; set; }
        public Nullable<int> TimeLimit { get; set; }
        public byte CountdownUnit { get; set; }
        public bool IsCountdown { get; set; }
        public string AdvertisingPosition { get; set; }
        public string AdvertisingContent { get; set; }
        public bool IsAllUser { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<byte> AmountRange { get; set; }
        public Nullable<byte> SellType { get; set; }
        public Nullable<byte> PayType { get; set; }
        public bool IsEnableAmount { get; set; }
        public bool IsEnableSell { get; set; }
        public bool IsEnablePay { get; set; }
        public bool IsEnable { get; set; }
        public string ActivityDescription { get; set; }
        public Nullable<byte> SimplePicture { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string AddAuthor { get; set; }
        public string UpdateAuthor { get; set; }
    }
}
