//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoMarKet_ActiveDetails
    {
        public string ID { get; set; }
        public string PromptlyConfigId { get; set; }
        public string ActivityName { get; set; }
        public string GoodId { get; set; }
        public Nullable<decimal> ProNowPrice { get; set; }
        public Nullable<int> GoodNum { get; set; }
        public Nullable<byte> PurchaseLimit { get; set; }
        public Nullable<byte> SingleLimit { get; set; }
        public string Url { get; set; }
        public Nullable<decimal> ProOldPrice { get; set; }
        public bool IsEnableActivityName { get; set; }
        public bool IsEnableProOldPrice { get; set; }
        public bool IsEnableProNowPrice { get; set; }
    }
}
