//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classify
    {
        public int Id { get; set; }
        public int PId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Remark { get; set; }
        public int SortIndex { get; set; }
        public int ChildrenCount { get; set; }
        public int Depth { get; set; }
        public string TreePath { get; set; }
        public bool IsSystem { get; set; }
        public string Settings { get; set; }
        public string Icon { get; set; }
        public string ImgUrl { get; set; }
        public short RootType { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
    }
}
