//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public long Id { get; set; }
        public short ConType { get; set; }
        public string ShowName { get; set; }
        public int Sort { get; set; }
        public string SetContent { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
    }
}
