//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SharemallEntities : DbContext
    {
        public SharemallEntities()
            : base("name=SharemallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad_AttentionAdv> Ad_AttentionAdv { get; set; }
        public virtual DbSet<Ad_Model> Ad_Model { get; set; }
        public virtual DbSet<Ad_ModelDetaile> Ad_ModelDetaile { get; set; }
        public virtual DbSet<Ad_Section> Ad_Section { get; set; }
        public virtual DbSet<Ad_SectionDetaile> Ad_SectionDetaile { get; set; }
        public virtual DbSet<Ad_ShareOrAttention> Ad_ShareOrAttention { get; set; }
        public virtual DbSet<Ad_Temple> Ad_Temple { get; set; }
        public virtual DbSet<Ad_UserFirst> Ad_UserFirst { get; set; }
        public virtual DbSet<Ad_UserFirstShare> Ad_UserFirstShare { get; set; }
        public virtual DbSet<AutoMarKet_ActiveDetails> AutoMarKet_ActiveDetails { get; set; }
        public virtual DbSet<AutoMarket_ActiveTime> AutoMarket_ActiveTime { get; set; }
        public virtual DbSet<AutoMarKet_OrderRecord> AutoMarKet_OrderRecord { get; set; }
        public virtual DbSet<AutoMarket_PromptlyConfig> AutoMarket_PromptlyConfig { get; set; }
        public virtual DbSet<Classify> Classify { get; set; }
        public virtual DbSet<Configuration> Configuration { get; set; }
        public virtual DbSet<Configuration_Child> Configuration_Child { get; set; }
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<enrollment> enrollment { get; set; }
        public virtual DbSet<MasterMessage> MasterMessage { get; set; }
        public virtual DbSet<Msg_WeiXinConfig> Msg_WeiXinConfig { get; set; }
        public virtual DbSet<Msg_WeiXinConfigHistory> Msg_WeiXinConfigHistory { get; set; }
        public virtual DbSet<Msg_WeiXinPushData> Msg_WeiXinPushData { get; set; }
        public virtual DbSet<Msg_WeiXinTemplate> Msg_WeiXinTemplate { get; set; }
        public virtual DbSet<New_Category> New_Category { get; set; }
        public virtual DbSet<New_News> New_News { get; set; }
        public virtual DbSet<Shop_ActionCondition> Shop_ActionCondition { get; set; }
        public virtual DbSet<Shop_ActionResult> Shop_ActionResult { get; set; }
        public virtual DbSet<Shop_ActionRule> Shop_ActionRule { get; set; }
        public virtual DbSet<Shop_ActionUserProGIF> Shop_ActionUserProGIF { get; set; }
        public virtual DbSet<Shop_Active> Shop_Active { get; set; }
        public virtual DbSet<Shop_ActiveAmount> Shop_ActiveAmount { get; set; }
        public virtual DbSet<Shop_ActiveProduct> Shop_ActiveProduct { get; set; }
        public virtual DbSet<Shop_ActiveProGIF> Shop_ActiveProGIF { get; set; }
        public virtual DbSet<Shop_ActiveType> Shop_ActiveType { get; set; }
        public virtual DbSet<Shop_Advertise> Shop_Advertise { get; set; }
        public virtual DbSet<Shop_AttributeValues> Shop_AttributeValues { get; set; }
        public virtual DbSet<Shop_Category> Shop_Category { get; set; }
        public virtual DbSet<Shop_Channel> Shop_Channel { get; set; }
        public virtual DbSet<Shop_CompanyActiveType> Shop_CompanyActiveType { get; set; }
        public virtual DbSet<Shop_CompanyCollect> Shop_CompanyCollect { get; set; }
        public virtual DbSet<Shop_CompanyPanel> Shop_CompanyPanel { get; set; }
        public virtual DbSet<Shop_DeliveryConfig> Shop_DeliveryConfig { get; set; }
        public virtual DbSet<Shop_Goods> Shop_Goods { get; set; }
        public virtual DbSet<Shop_GoosTag> Shop_GoosTag { get; set; }
        public virtual DbSet<Shop_Invoice> Shop_Invoice { get; set; }
        public virtual DbSet<Shop_KelailePrintSetting> Shop_KelailePrintSetting { get; set; }
        public virtual DbSet<Shop_LocalOrderSet> Shop_LocalOrderSet { get; set; }
        public virtual DbSet<Shop_OpenClose> Shop_OpenClose { get; set; }
        public virtual DbSet<Shop_Order> Shop_Order { get; set; }
        public virtual DbSet<Shop_OrderLineUp> Shop_OrderLineUp { get; set; }
        public virtual DbSet<Shop_OrderProcess> Shop_OrderProcess { get; set; }
        public virtual DbSet<Shop_OrderRoom> Shop_OrderRoom { get; set; }
        public virtual DbSet<Shop_OrderShop> Shop_OrderShop { get; set; }
        public virtual DbSet<Shop_OrderStatistics> Shop_OrderStatistics { get; set; }
        public virtual DbSet<Shop_PrinterSetting> Shop_PrinterSetting { get; set; }
        public virtual DbSet<Shop_ProAllowSellType> Shop_ProAllowSellType { get; set; }
        public virtual DbSet<Shop_ProCollect> Shop_ProCollect { get; set; }
        public virtual DbSet<Shop_ProComment> Shop_ProComment { get; set; }
        public virtual DbSet<Shop_ProductAttributes> Shop_ProductAttributes { get; set; }
        public virtual DbSet<Shop_ProductTypes> Shop_ProductTypes { get; set; }
        public virtual DbSet<Shop_ProductTypesAttributes> Shop_ProductTypesAttributes { get; set; }
        public virtual DbSet<Shop_ProGIF> Shop_ProGIF { get; set; }
        public virtual DbSet<Shop_ProMiaoSha> Shop_ProMiaoSha { get; set; }
        public virtual DbSet<Shop_ProTuan> Shop_ProTuan { get; set; }
        public virtual DbSet<Shop_ProTuanProTuanType> Shop_ProTuanProTuanType { get; set; }
        public virtual DbSet<Shop_ProTuanType> Shop_ProTuanType { get; set; }
        public virtual DbSet<Shop_PublicNo> Shop_PublicNo { get; set; }
        public virtual DbSet<Shop_Room> Shop_Room { get; set; }
        public virtual DbSet<Shop_SeachKey> Shop_SeachKey { get; set; }
        public virtual DbSet<Shop_ShopCar> Shop_ShopCar { get; set; }
        public virtual DbSet<Shop_ShopHistory> Shop_ShopHistory { get; set; }
        public virtual DbSet<Shop_ShopPic> Shop_ShopPic { get; set; }
        public virtual DbSet<Shop_StoreShow> Shop_StoreShow { get; set; }
        public virtual DbSet<Shop_Tag> Shop_Tag { get; set; }
        public virtual DbSet<Shop_UserStatistics> Shop_UserStatistics { get; set; }
        public virtual DbSet<ShopMobileBind> ShopMobileBind { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<Sys_Aptitude> Sys_Aptitude { get; set; }
        public virtual DbSet<Sys_BtnValue> Sys_BtnValue { get; set; }
        public virtual DbSet<Sys_BusinessCircle> Sys_BusinessCircle { get; set; }
        public virtual DbSet<Sys_City> Sys_City { get; set; }
        public virtual DbSet<Sys_Company> Sys_Company { get; set; }
        public virtual DbSet<Sys_CompanyBankAccount> Sys_CompanyBankAccount { get; set; }
        public virtual DbSet<Sys_CompanyCategory> Sys_CompanyCategory { get; set; }
        public virtual DbSet<Sys_CompanyExtInfo> Sys_CompanyExtInfo { get; set; }
        public virtual DbSet<Sys_CompanyFun> Sys_CompanyFun { get; set; }
        public virtual DbSet<Sys_CompanyInfoModfy> Sys_CompanyInfoModfy { get; set; }
        public virtual DbSet<Sys_CompanyLevelNum> Sys_CompanyLevelNum { get; set; }
        public virtual DbSet<Sys_CompanyLinker> Sys_CompanyLinker { get; set; }
        public virtual DbSet<Sys_CompanyMsgCenter> Sys_CompanyMsgCenter { get; set; }
        public virtual DbSet<Sys_CompanyPaySet> Sys_CompanyPaySet { get; set; }
        public virtual DbSet<Sys_CompanyReturns> Sys_CompanyReturns { get; set; }
        public virtual DbSet<Sys_CompanySelfCategory> Sys_CompanySelfCategory { get; set; }
        public virtual DbSet<Sys_CompanySellProType> Sys_CompanySellProType { get; set; }
        public virtual DbSet<Sys_CompanySellType> Sys_CompanySellType { get; set; }
        public virtual DbSet<Sys_CompanySellType2Pay> Sys_CompanySellType2Pay { get; set; }
        public virtual DbSet<Sys_CompanyTag> Sys_CompanyTag { get; set; }
        public virtual DbSet<Sys_CompanyTemp> Sys_CompanyTemp { get; set; }
        public virtual DbSet<Sys_Feedback> Sys_Feedback { get; set; }
        public virtual DbSet<Sys_FirstRegister> Sys_FirstRegister { get; set; }
        public virtual DbSet<Sys_Flow> Sys_Flow { get; set; }
        public virtual DbSet<Sys_FlowSetting> Sys_FlowSetting { get; set; }
        public virtual DbSet<Sys_Fun> Sys_Fun { get; set; }
        public virtual DbSet<Sys_FunLinkBtnValue> Sys_FunLinkBtnValue { get; set; }
        public virtual DbSet<Sys_hatarea> Sys_hatarea { get; set; }
        public virtual DbSet<Sys_hatcity> Sys_hatcity { get; set; }
        public virtual DbSet<Sys_hatprovince> Sys_hatprovince { get; set; }
        public virtual DbSet<Sys_Images> Sys_Images { get; set; }
        public virtual DbSet<Sys_Master> Sys_Master { get; set; }
        public virtual DbSet<Sys_MasterRole> Sys_MasterRole { get; set; }
        public virtual DbSet<Sys_OnlinePaySelct> Sys_OnlinePaySelct { get; set; }
        public virtual DbSet<Sys_OnlinePayType> Sys_OnlinePayType { get; set; }
        public virtual DbSet<Sys_OpenCloseRecord> Sys_OpenCloseRecord { get; set; }
        public virtual DbSet<Sys_Organizational> Sys_Organizational { get; set; }
        public virtual DbSet<Sys_PeopleService> Sys_PeopleService { get; set; }
        public virtual DbSet<Sys_PushCityInfo> Sys_PushCityInfo { get; set; }
        public virtual DbSet<Sys_PushInfo> Sys_PushInfo { get; set; }
        public virtual DbSet<Sys_PushUser> Sys_PushUser { get; set; }
        public virtual DbSet<Sys_RegVerification> Sys_RegVerification { get; set; }
        public virtual DbSet<Sys_RequestTime> Sys_RequestTime { get; set; }
        public virtual DbSet<Sys_Role> Sys_Role { get; set; }
        public virtual DbSet<Sys_RoleFun> Sys_RoleFun { get; set; }
        public virtual DbSet<Sys_RoleRangeData> Sys_RoleRangeData { get; set; }
        public virtual DbSet<Sys_SearchShopTable> Sys_SearchShopTable { get; set; }
        public virtual DbSet<Sys_SearchTable> Sys_SearchTable { get; set; }
        public virtual DbSet<Sys_SearchTableOrder> Sys_SearchTableOrder { get; set; }
        public virtual DbSet<Sys_Selltype> Sys_Selltype { get; set; }
        public virtual DbSet<Sys_SetingAppMessage> Sys_SetingAppMessage { get; set; }
        public virtual DbSet<Sys_Setting> Sys_Setting { get; set; }
        public virtual DbSet<Sys_SMSModel> Sys_SMSModel { get; set; }
        public virtual DbSet<Sys_SMSRecord> Sys_SMSRecord { get; set; }
        public virtual DbSet<Sys_StoreCloseRemind> Sys_StoreCloseRemind { get; set; }
        public virtual DbSet<Sys_StoreOpenRemind> Sys_StoreOpenRemind { get; set; }
        public virtual DbSet<Sys_Tag> Sys_Tag { get; set; }
        public virtual DbSet<Sys_ThirdUser> Sys_ThirdUser { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Sys_UserAlwayArea> Sys_UserAlwayArea { get; set; }
        public virtual DbSet<Sys_UserColloctType> Sys_UserColloctType { get; set; }
        public virtual DbSet<Sys_UserGroup> Sys_UserGroup { get; set; }
        public virtual DbSet<Sys_UserTakeAddr> Sys_UserTakeAddr { get; set; }
        public virtual DbSet<Sys_WeiXinPrepayOrder> Sys_WeiXinPrepayOrder { get; set; }
        public virtual DbSet<Sys_WxAccessToken> Sys_WxAccessToken { get; set; }
        public virtual DbSet<Sys_WxJsApiToken> Sys_WxJsApiToken { get; set; }
        public virtual DbSet<Sys_WxUserMap> Sys_WxUserMap { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SysLogEx> SysLogEx { get; set; }
        public virtual DbSet<SysPayCallBackLog> SysPayCallBackLog { get; set; }
        public virtual DbSet<Sys_Rebate> Sys_Rebate { get; set; }
    }
}
