//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg_WeiXinPushData
    {
        public string ID { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public string ModelId { get; set; }
        public string AccessToken { get; set; }
        public string OpenId { get; set; }
        public byte SendStatus { get; set; }
        public short SendCount { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<int> ResultId { get; set; }
        public string CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime OrderTime { get; set; }
        public string GoodNames { get; set; }
        public decimal OrderAmount { get; set; }
        public string FirstDataStr { get; set; }
        public string RemarkDataStr { get; set; }
        public string DetailURL { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
    }
}
