//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg_WeiXinTemplate
    {
        public string ID { get; set; }
        public string WeiXinConfigId { get; set; }
        public string CompanyId { get; set; }
        public string FirstDataStr { get; set; }
        public string RemarkDataStr { get; set; }
        public string DetailUrl { get; set; }
        public byte IsAllOrderType { get; set; }
        public Nullable<byte> SellType { get; set; }
        public Nullable<byte> PayType { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyBy { get; set; }
        public byte IsEnable { get; set; }
        public byte TempalteType { get; set; }
    }
}
