//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg_WeiXinConfig
    {
        public string ID { get; set; }
        public string CompanyId { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public string ModelId { get; set; }
        public string ModelCode { get; set; }
        public string ModelTitle { get; set; }
        public byte IsAllOrderType { get; set; }
        public byte IsEnable { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyBy { get; set; }
    }
}
