//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ShopCar
    {
        public string Id { get; set; }
        public string UserID { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> SellType { get; set; }
        public string ActiveID { get; set; }
        public string ProID { get; set; }
        public Nullable<int> ProNumber { get; set; }
        public string ProProperty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> isSelect { get; set; }
    }
}
