//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Advertise
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Type { get; set; }
        public string Img { get; set; }
        public string CID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string RelatedBusinesses { get; set; }
        public string Content { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreaterID { get; set; }
        public string CreaterName { get; set; }
        public int Position { get; set; }
        public int TriggerType { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int ActiveType { get; set; }
        public string RelateShopName { get; set; }
        public string RelateShopId { get; set; }
        public int SortIndex { get; set; }
    }
}
