//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ProComment
    {
        public string ID { get; set; }
        public Nullable<double> Rank { get; set; }
        public string Info { get; set; }
        public Nullable<int> Type { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Reconment { get; set; }
        public Nullable<System.DateTime> ReAddtime { get; set; }
        public string ProId { get; set; }
        public Nullable<bool> IsNoName { get; set; }
    }
}
