//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_KelailePrintSetting
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ResultMessage { get; set; }
        public Nullable<int> ResultCode { get; set; }
        public string TradeNumber { get; set; }
        public string WxTradeNumber { get; set; }
        public string OrderTime { get; set; }
    }
}
