//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Goods
    {
        public string ID { get; set; }
        public string ProdectTypeId { get; set; }
        public string CategoryID { get; set; }
        public string hyId { get; set; }
        public string ProName { get; set; }
        public string ProPic { get; set; }
        public Nullable<decimal> ProOldPrice { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public Nullable<decimal> ProNowPrice { get; set; }
        public string ProInfo { get; set; }
        public Nullable<int> ProStock { get; set; }
        public Nullable<int> ProHit { get; set; }
        public string ProBrief { get; set; }
        public string CompanyId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string ProKey { get; set; }
        public Nullable<int> DiscountRate { get; set; }
        public Nullable<int> IsRecommend { get; set; }
        public Nullable<int> IsSpecial { get; set; }
        public Nullable<int> IsWaitConfirm { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsTemplate { get; set; }
        public Nullable<int> SaleCount { get; set; }
        public Nullable<double> AverageComment { get; set; }
        public Nullable<int> CompanyClassify { get; set; }
        public Nullable<decimal> Shipment { get; set; }
        public Nullable<decimal> PackagingCost { get; set; }
    }
}
