//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_OrderLineUp
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string Sex { get; set; }
        public Nullable<int> PepoleNum { get; set; }
        public string Tel { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsSmsVoice { get; set; }
        public string AddUser { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> IsConfirm { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<int> WaitPepoleNum { get; set; }
    }
}
