//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_DeliveryConfig
    {
        public string Id { get; set; }
        public string CompanyId { get; set; }
        public int DeliveryTimeType { get; set; }
        public Nullable<System.TimeSpan> FirstStartTime { get; set; }
        public Nullable<System.TimeSpan> FirstEndTime { get; set; }
        public Nullable<System.TimeSpan> SecondStartTime { get; set; }
        public Nullable<System.TimeSpan> SecondEndTime { get; set; }
        public Nullable<System.TimeSpan> ThirdStartTime { get; set; }
        public Nullable<System.TimeSpan> ThirdEndTime { get; set; }
        public int DeliveryDistanceType { get; set; }
        public Nullable<double> DeliveryDistance { get; set; }
        public Nullable<decimal> DeliveryDistanceAmount { get; set; }
        public int PackType { get; set; }
        public int IsFreePack { get; set; }
        public Nullable<decimal> FreePackAmount { get; set; }
        public int DeliveryAmountType { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public int IsFreeDelivery { get; set; }
        public Nullable<decimal> FreeDeliveryAmount { get; set; }
        public string Remark { get; set; }
        public string LeaveMsg { get; set; }
        public int Status { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
