//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ProMiaoSha
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Info { get; set; }
        public Nullable<System.DateTime> UseStartTime { get; set; }
        public Nullable<System.DateTime> UseEndTime { get; set; }
        public string Image { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> MustNum { get; set; }
        public Nullable<int> AllowNum { get; set; }
        public string ProId { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CreaterID { get; set; }
        public string CreaterName { get; set; }
        public Nullable<bool> IsPlatform { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string BelongCompanyId { get; set; }
        public bool isDisplay { get; set; }
        public bool IsFocus { get; set; }
    }
}
