//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Order
    {
        public Shop_Order()
        {
            this.Sys_CompanyReturns = new HashSet<Sys_CompanyReturns>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> Status { get; set; }
        public string BuyerUserName { get; set; }
        public string BuyerAddress { get; set; }
        public string BuyerAddressId { get; set; }
        public string BuyerPhone { get; set; }
        public string BuyerTel { get; set; }
        public string PostCode { get; set; }
        public Nullable<decimal> AccountPrice { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string ActUserId { get; set; }
        public string OrderRemark { get; set; }
        public string UserId { get; set; }
        public string CompanyId { get; set; }
        public string ActRemark { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string PayId { get; set; }
        public string PayTypeId { get; set; }
        public Nullable<int> ReceiptWay { get; set; }
        public string InvoiceTitle { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<int> ClientType { get; set; }
        public string ClientMobileType { get; set; }
        public string InvoiceBody { get; set; }
        public Nullable<int> GoodCount { get; set; }
        public bool Is24Alert { get; set; }
        public int BackStatus { get; set; }
        public bool IsRefund { get; set; }
        public bool IsMessageTip { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public string QROrderURL { get; set; }
        public string ValidateCode { get; set; }
        public Nullable<decimal> FavorablePrice { get; set; }
        public string OrderLot { get; set; }
        public int PrintCount { get; set; }
        public Nullable<short> PrintFlag { get; set; }
        public short PaymentStatus { get; set; }
        public short RefundStatus { get; set; }
        public Nullable<int> PublicNo { get; set; }
        public Nullable<bool> IsOutOfRang { get; set; }
        public Nullable<decimal> TotalShipmentAmount { get; set; }
        public Nullable<decimal> TotalPacktAmount { get; set; }
        public string TableNo { get; set; }
        public Nullable<decimal> GoodAccountPrice { get; set; }
        public Nullable<int> OrderCloseType { get; set; }
    
        public virtual ICollection<Sys_CompanyReturns> Sys_CompanyReturns { get; set; }
    }
}
