//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ActionUserProGIF
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public string CompanyID { get; set; }
        public string ActiveID { get; set; }
        public Nullable<int> SellTypeID { get; set; }
        public string ProGifID { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
