//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ProductTypesAttributes
    {
        public Shop_ProductTypesAttributes()
        {
            this.Shop_AttributeValues = new HashSet<Shop_AttributeValues>();
            this.Shop_ProductAttributes = new HashSet<Shop_ProductAttributes>();
        }
    
        public string AttributeId { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> DisplaySequence { get; set; }
        public string TypeId { get; set; }
        public Nullable<int> UsageMode { get; set; }
        public Nullable<bool> UseAttributeImage { get; set; }
        public Nullable<bool> UserDefinedPic { get; set; }
    
        public virtual ICollection<Shop_AttributeValues> Shop_AttributeValues { get; set; }
        public virtual ICollection<Shop_ProductAttributes> Shop_ProductAttributes { get; set; }
    }
}
