//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Channel
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string ShopUrl { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
