//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ActionRule
    {
        public string ID { get; set; }
        public string ActiveID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public string ConditionValue { get; set; }
        public Nullable<int> ConditionsType { get; set; }
        public Nullable<int> ResultID { get; set; }
        public string ResultValue { get; set; }
        public Nullable<int> ResultType { get; set; }
        public Nullable<int> AbatementForm { get; set; }
        public Nullable<bool> IsAllProduct { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
