//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ProGIF
    {
        public string ID { get; set; }
        public string ProName { get; set; }
        public string ProPic { get; set; }
        public Nullable<decimal> ProOldPrice { get; set; }
        public Nullable<decimal> ProNowPrice { get; set; }
        public string ProInfo { get; set; }
        public Nullable<int> ProStock { get; set; }
        public string ProBrief { get; set; }
        public string CompanyID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreateorID { get; set; }
        public string ImageUrl { get; set; }
        public string CategoryId { get; set; }
    }
}
