//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_OrderShop
    {
        public string OrderCode { get; set; }
        public string ProId { get; set; }
        public string ProName { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NowPrice { get; set; }
        public Nullable<int> BuyNum { get; set; }
        public int IsTuan { get; set; }
        public string TuanId { get; set; }
        public string PropertyValue { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<bool> IsComment { get; set; }
        public Nullable<int> ActiveType { get; set; }
        public string ActiveId { get; set; }
        public long Id { get; set; }
    }
}
