//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CompanyExtInfo
    {
        public string Id { get; set; }
        public string CompanyId { get; set; }
        public string BottomTitle { get; set; }
        public Nullable<int> PushNum { get; set; }
        public Nullable<int> ShopNum { get; set; }
        public Nullable<int> ShopOnNum { get; set; }
        public Nullable<int> IsSupportInvoice { get; set; }
        public string PushMsgType { get; set; }
        public Nullable<int> RutureDay { get; set; }
        public Nullable<int> CloseDay { get; set; }
        public short IsShowFocus { get; set; }
        public string SellTypeInfo { get; set; }
        public decimal ShippingAmount { get; set; }
        public string Phone { get; set; }
        public int ReceivePeriod { get; set; }
        public decimal ReceiveMoney { get; set; }
        public decimal ReceiveRate { get; set; }
        public Nullable<int> IsAutoClose { get; set; }
        public Nullable<int> AutoCloseHour { get; set; }
    }
}
