//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Master
    {
        public string ID { get; set; }
        public string LoginName { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string CID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LoginIp { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public byte[] Tfs { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<int> LoginNum { get; set; }
        public string CreaterId { get; set; }
        public string CreaterName { get; set; }
        public string OrganizaId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> PaltForm { get; set; }
        public string BDUserID { get; set; }
        public string BDChannelID { get; set; }
    }
}
