//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Fun
    {
        public string ID { get; set; }
        public Nullable<int> FunID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string ParentID { get; set; }
        public Nullable<int> FunSort { get; set; }
        public string FunName { get; set; }
        public string PageUrl { get; set; }
        public string ClassName { get; set; }
        public Nullable<bool> IsForbid { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public byte[] Ts { get; set; }
        public string iconCls { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<bool> isChild { get; set; }
        public bool isCheckRole { get; set; }
        public string Code { get; set; }
    }
}
