//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_PushUser
    {
        public string PushUserId { get; set; }
        public string PropelID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<int> Msgstate { get; set; }
    }
}
