//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CompanyTemp
    {
        public string ID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyAddress { get; set; }
        public string ComLon { get; set; }
        public string ComLat { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AddType { get; set; }
        public string BelongCompanyId { get; set; }
        public Nullable<int> SendNum { get; set; }
        public Nullable<int> SendType { get; set; }
        public string CompanyId { get; set; }
        public Nullable<System.DateTime> FistSendTime { get; set; }
        public Nullable<System.DateTime> LastSendTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> ShowType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
