//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Company
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public Nullable<int> Level { get; set; }
        public string Path { get; set; }
        public Nullable<int> Attribute { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> RegisiTime { get; set; }
        public Nullable<decimal> ReegistMoney { get; set; }
        public string CityId { get; set; }
        public string LinkUser { get; set; }
        public string LegalPerson { get; set; }
        public string Type { get; set; }
        public string Nature { get; set; }
        public string Introduction { get; set; }
        public string Reark { get; set; }
        public Nullable<int> Status { get; set; }
        public string OpenedTime { get; set; }
        public string ClosedTime { get; set; }
        public Nullable<bool> DayStatus { get; set; }
        public string CloseStoreReason { get; set; }
        public string SmsAcount { get; set; }
        public string SmsPassWord { get; set; }
        public string ParentId { get; set; }
        public Nullable<bool> IsOnlinePay { get; set; }
        public string CreateCompanyId { get; set; }
        public string CreaterUserId { get; set; }
        public Nullable<int> LevelNum { get; set; }
        public string ComPLon { get; set; }
        public string CompLat { get; set; }
        public Nullable<long> HitNum { get; set; }
        public string MasterId { get; set; }
        public string CityareaId { get; set; }
        public string CityAreaBCId { get; set; }
        public string BackPic { get; set; }
        public string ProPic { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public string Pact { get; set; }
        public string QRCodeImage { get; set; }
        public string QRCodeDefaultImage { get; set; }
        public string SerialPorts { get; set; }
        public Nullable<bool> ShareTfs { get; set; }
        public Nullable<double> DeliveryDistance { get; set; }
        public Nullable<decimal> MapLat { get; set; }
        public Nullable<decimal> MapLng { get; set; }
        public string RandomNumber { get; set; }
        public int BusinessType { get; set; }
        public short BusinessStatus { get; set; }
        public Nullable<int> StockWarning { get; set; }
        public Nullable<int> WeiXinShopSetType { get; set; }
    }
}
