//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ThirdUser
    {
        public string ID { get; set; }
        public Nullable<int> TType { get; set; }
        public string TName { get; set; }
        public string TUID { get; set; }
        public string TSysUserID { get; set; }
    }
}
