//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_RegVerification
    {
        public string ID { get; set; }
        public string Tel { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public int TypeInt { get; set; }
        public Nullable<int> Counter { get; set; }
    }
}
