//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CompanyPaySet
    {
        public string ID { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> PayTypeID { get; set; }
        public string Partner { get; set; }
        public string Seller { get; set; }
        public string RsaPrivate { get; set; }
        public string RsaAlipayPublic { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
    }
}
