//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public string ID { get; set; }
        public string UName { get; set; }
        public string UCID { get; set; }
        public string UPwd { get; set; }
        public string UNickname { get; set; }
        public string UEmail { get; set; }
        public string UTel { get; set; }
        public string UPhone { get; set; }
        public Nullable<bool> USex { get; set; }
        public string UJobName { get; set; }
        public string UHeadImg { get; set; }
        public Nullable<System.DateTime> UBirthday { get; set; }
        public string USignature { get; set; }
        public Nullable<int> UState { get; set; }
        public Nullable<System.DateTime> UCreateTime { get; set; }
        public Nullable<System.DateTime> ULastLoginTime { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> ULoginCount { get; set; }
        public Nullable<int> UAllPoint { get; set; }
        public Nullable<int> UNowPoint { get; set; }
        public string UUserGroup { get; set; }
        public Nullable<int> RegistPaltForm { get; set; }
        public Nullable<int> ComeFrom { get; set; }
        public string ComanyName { get; set; }
        public string MobileCode { get; set; }
        public string CityId { get; set; }
        public bool IsActiveFocus { get; set; }
        public Nullable<short> UserType { get; set; }
        public Nullable<int> UserNum { get; set; }
        public string GUserID { get; set; }
    }
}
