//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Flow
    {
        public string ID { get; set; }
        public string FlowName { get; set; }
        public string FlowSendUserId { get; set; }
        public string FlowSendUserName { get; set; }
        public Nullable<System.DateTime> FlowSendTime { get; set; }
        public Nullable<int> FlowStatus { get; set; }
        public Nullable<int> FlowCallBack { get; set; }
        public string CompanyId { get; set; }
        public string FlowStep { get; set; }
        public string HasFlow { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string BackRemark { get; set; }
        public string ForId { get; set; }
        public Nullable<bool> IsMessageTip { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
