//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_BtnValue
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Value { get; set; }
        public string ActionName { get; set; }
        public string IConName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> BtnType { get; set; }
        public string NameTip { get; set; }
    }
}
