//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_OnlinePayType
    {
        public int OID { get; set; }
        public string OPayTypeName { get; set; }
        public string OUrl { get; set; }
        public Nullable<int> OPayFit { get; set; }
        public string PayName { get; set; }
        public string PayLogo { get; set; }
    }
}
