//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_PushInfo
    {
        public string PropelID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string PTitle { get; set; }
        public string Info { get; set; }
        public string CorrelativeID { get; set; }
        public string CompanyID { get; set; }
        public string CreatorID { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<int> Model { get; set; }
        public string State { get; set; }
        public string MsgEntName { get; set; }
        public Nullable<int> LateTime { get; set; }
        public Nullable<int> ReceiverObject { get; set; }
    }
}
