//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserAlwayArea
    {
        public string ID { get; set; }
        public string UserId { get; set; }
        public string AName { get; set; }
        public string Lon { get; set; }
        public string Lat { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string DetailAddr { get; set; }
        public int Restype { get; set; }
    }
}
