//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADH.DevHelperWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLogEx
    {
        public long Id { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string ThreadId { get; set; }
        public string LogLevel { get; set; }
        public string Logger { get; set; }
        public string LogMessage { get; set; }
        public string LogException { get; set; }
    }
}
